name: create-repo-issue3
  
on: 
  workflow_call:
    inputs:
      title:
        description: 'Issue title'
        required: true
        type: string
      body:
        description: 'Issue body'
        required: true
        type: string
    outputs:
      issue-number:
        description: "The issue number"
        value: ${{ jobs.create-issue.outputs.i-num }}
        
jobs:
 
  create-issue:
    runs-on: ubuntu-latest
    # Map job outputs to step outputs
    outputs:
      i-num: ${{ steps.new-issue.outputs.inum }}
  
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        id: new-issue
        run: |
          response=$(curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.PAT }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "${{ inputs.title }}",
            "body": "${{ inputs.body }}"
            }' \
          --fail | jq '.number') 
          echo "number=$response"
          echo "inum=$response" >> $GITHUB_OUTPUT
         # echo "::set-output name=inum::$response"
    
  report-issue-number-local:
    runs-on: ubuntu-latest
    needs: create-issue
    steps:
      - run: echo ${{needs.create-issue.outputs.i-num}}
