name: Verify existence of CONTRIBUTING.md file

on:
  push:
  pull_request:
  pull_request_target:
  
  
jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: |
          [[ -f CONTRIBUTING.md ]] || ( echo "CONTRIBUTING.md file needs to be added to ${{ github.repository }} !" && exit 1 )
          
      
